CREATE TABLE DOCENTE (
    NOME VARCHAR(50);
    TELEFONE INT;
    CODIGODOCENTE INTE NOT NULL;
    PRIMARY KEY CODIGODOCENTE;
    FOREIGN KEY(CODIGOPROJETO  ) REFERENCES PROJETO(CODIGOPROJETO);
)

CREATE TABLE PROJETO (
    DESCRICAO VARCHAR(100);
    CODIGOPROJETO INT NOT NULL;
    PRIMARY KEY CODIGOPROJETO;
)

CREATE TABLE ALUNO (
    CPF INT;
    CODIGOALUNO INT NOT NULL;
    PRIMARY KEY CODIGOALUNO;
    FOREIGN KEY (CODIGOPROJETO) REFERENCES PROJETO(CODIGOPROJETO);
)