CREATE TABLE ALUNO (
    CODIGOALUNO int NOT NULL,
    NOME varchar (90) NOT NULL,
    SEXO vachar() NOT NULL,
    DTNASCIMENTO date NOT NULL,
    EMAIL varchar (30) NOT NULL,
    CONSTRAINT ALUNO_pk PRIMARY KEY (CODIGOALUNO),

    INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO, EMAIL) VALUES (1, 'José',' M', '28/07/2020', 'JFT@GMAIL.COM');
    INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (2, 'ANDREY COSTA FILHO', 'M', '20/10/1999', 'ANDREYCF@HOTMAIL. COM');
    INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO, EMAIL) VALUES (3, 'PATRICIA TORRES LOUREIRO', 'F', '20/10/1980', 'PTORRES@GMAIL.COM');
    INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO, EMAIL) VALUES (4, 'CARLA MARIA MACIEL', 'F','20/11/1996', NULL);
    INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (5, 'LEILA SANTANA COSTA', 'F','20/11/2001',NULL);
)
