CREATE TABLE FUNCIONARIO(
    CODIGOFUNCIONARIO PRIMARY KEY,
    NOME VARCHAR(50),
    SEXO VARCHAR(50),
    CPF INT(90),
    DTNASCIMENTO(30);
    

)
CREATE TABLE DEPENDENTES (
    NOME VARCAHR(50),
    DTNASCIMENTO(30),
    NR_DEPEDENTE INTEGER REFERENCES CODIGOFUNCIONARIO (NR);

)